### ISSUE TITLE
User Projects', Project Team's, and Project-Team Request's Models.

### ISSUE THREAD

**Issue by shahp98** [djunicode/Project-Finder#17]
Create the above mentioned models. You can refer [DJ-Comps-Skill-Finder's models](https://github.com/djunicode/DJ-Comps-Skill-Finder/blob/integrate/users/models.py)

If you have to refer to some other model which isn't present, define it.

**Comment by akksshah** [comment]
@parag1999 why haven't you reviewed it yet?
